fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "firewall": "git://github.com/puppetlabs/puppetlabs-firewall.git"
    "apache": "git://github.com/puppetlabs/puppetlabs-apache.git"
  symlinks:
    "pypi": "#{source_dir}"
